project-3/BusinessManagement/views/admin.py
import io
from flask import Blueprint, render_template, request, redirect, flash
from werkzeug.utils import secure_filename
from sql.db import DB
import traceback
from collections import Counter
import csv
admin = Blueprint('admin', __name__, url_prefix='/admin')

@admin.route("/import", methods=["GET","POST"])
def importCSV():
    if request.method == "POST":
        if 'file' not in request.files:
            return redirect(request.url)
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash('No selected file', "warning")
            return redirect(request.url)
        # TODO importcsv-1 check that it's a .csv file, return a proper flash message if it's not
        

        if file.filename.split('.')[-1] != 'csv':
            flash('Uploaded file is not CSV file', 'danger')
            return redirect(request.url)
        if file and secure_filename(file.filename):
            companies = []
            employees = []
            # DON'T EDIT
            company_query = """
            INSERT INTO IS601_MP3_Companies (name, address, city, country, state, zip, website)
                        VALUES (%(name)s, %(address)s, %(city)s, %(country)s, %(state)s, %(zip)s, %(website)s)
                        ON DUPLICATE KEY UPDATE 
                        address=values(address),
                        city=values(city),
                        country=values(country),
                        state=values(state),
                        zip=values(zip),
                        website=values(website)
            """
            # DON'T EDIT
            employee_query = """
             INSERT INTO IS601_MP3_Employees (first_name, last_name, email, company_id)
                        VALUES (%(first_name)s, %(last_name)s, %(email)s, (SELECT id FROM IS601_MP3_Companies WHERE name = %(company_name)s LIMIT 1))
                        ON DUPLICATE KEY UPDATE first_name=%(first_name)s, 
                        last_name = %(last_name)s, email = %(email)s, 
                        company_id = (SELECT id FROM IS601_MP3_Companies WHERE name=%(company_name)s LIMIT 1)
            """
            # Note: this reads the file as a stream instead of requiring us to save it
            stream = io.TextIOWrapper(file.stream._file, "UTF8", newline=None)
            
            for row in csv.DictReader(stream, delimiter=','):
                # print(row) #example
                # TODO importcsv-3 extract company data and append to company list as a dict only with company data
                if (row["company_name"].strip() != "" and row["address"].strip() != "" and row["city"].strip() != "" and row["country"].strip() != "" and row["state"].strip() != "" and row["zip"].strip() != "" and row["web"].strip() != ""):
                    companies.append({'name':row["company_name"], 'address':row["address"], 'city':row["city"], 'country':row["country"], 'state':row["state"], 'zip':row["zip"],
                 'website':row["web"]})
                # TODO importcsv-4 extract employee data and append to employee list as a dict only with employee data
                

                if (row["first_name"].strip() != "" and row["last_name"].strip() != "" and row['email'].strip() != "" and row['company_name'].strip() != ""):
                    employees.append({'first_name':row["first_name"], 'last_name':row["last_name"], 'email':row['email'], 'company_name':row['company_name']})

            if len(companies) > 0:
                print(f"Inserting or updating {len(companies)} companies")
                try:
                    result = DB.insertMany(company_query, companies)
                    # TODO importcsv-5 display flash message about number of companies inserted
                    flash(f'{len(companies)} companies have been inserted', 'success')
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                # TODO importcsv-6 display flash message (info) that no companies were loaded
                # pass
                flash("No companies are loaded")
            if len(employees) > 0:
                print(f"Inserting or updating {len(employees)} employees")
                try:
                    result = DB.insertMany(employee_query, employees)
                    # TODO importcsv-7 display flash message about number of employees loaded
                    flash(f'{len(employees)} employees have been inserted', "success")
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                # TODO importcsv-8 display flash message (info) that no companies were loaded
                

                flash("No employees are loaded")
    return render_template("upload.html")

project-3/BusinessManagement/views/company.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from sql.db import DB
company = Blueprint('company', __name__, url_prefix='/company')

@company.route("/search", methods=["GET"])
def search():
    rows = []
    # DO NOT DELETE PROVIDED COMMENTS
    # TODO search-1 retrieve id, name, address, city, country, state, zip, website, employee count for the company
    # don't do SELECT *
    

    ## Select query to get company data for search
    query = "SELECT c.id, c.name, c.address, c.city, c.country, c.state, c.zip, c.website, COUNT(e.id) AS employees FROM IS601_MP3_Companies c LEFT JOIN IS601_MP3_Employees e ON e.company_id = c.id WHERE 1=1"
    print(query)
    args = [] # <--- append values to replace %s placeholders
    allowed_columns = ["name", "city", "country", "state"]
    allowed_list = [(v, v) for v in allowed_columns]
    # TODO search-2 get name, country, state, column, order, limit request args
    

    ## retieving the arguments
    name = request.args.get('name')
    country = request.args.get('country')
    state = request.args.get('state')
    column = request.args.get('column')
    order = request.args.get('order')
    limit = request.args.get('limit')
    ## appending the respective arguments and flash message for limit
    # TODO search-3 append a LIKE filter for name if provided
    if name:
        query += " AND c.name like %s"
        args.append(f"%{name}%")
    # TODO search-4 append an equality filter for country if provided
    if country:
        query += " AND c.country like %s"
        args.append(f"%{country}%")
    # TODO search-5 append an equality filter for state if provided
    if state:
        query += " AND c.state like %s"
        args.append(f"%{state}%")
    query += " GROUP BY c.id"
    # TODO search-6 append sorting if column and order are provided and within the allows columsn and allowed order asc,desc
    if column and order:
        if column in allowed_columns and order in ["asc", "desc"]:
            query += f" ORDER BY {column} {order}"
    # TODO search-7 append limit (default 10) or limit greater than 1 and less than or equal to 100
    # TODO search-8 provide a proper error message if limit isn't a number or if it's out of bounds
    if limit and int(limit) > 0 and int(limit) <= 100:
        query += " LIMIT %s"
        args.append(int(limit))
    elif limit and (int(limit) <= 0 or int(limit) > 100):
        flash("Enter the limit between 1 and 100", 'warning')

    print("query",query)
    print("args", args)
    try:
        result = DB.selectAll(query, *args)
        #print(result)
        if result.status:
            rows = result.rows
    except Exception as e:
        # TODO search-9 make message user friendly
        

        print(e)
        flash("Error occured, please check the data and try again", "danger")
    # hint: use allowed_columns in template to generate sort dropdown
    return render_template("list_companies.html", rows=rows, allowed_columns=allowed_list)

@company.route("/add", methods=["GET","POST"])
def add():
    if request.method == "POST":
        # TODO add-1 retrieve form data for name, address, city, state, country, zip, website
        
        # retrieving the form data
        name = request.form.get("name")
        address = request.form.get("address")
        city = request.form.get("city")
        zip = request.form.get("zip")
        website = request.form.get("website")
        country = request.form.get("country")
        state = request.form.get("state")
        # TODO add-2 name is required (flash proper error message)
        # TODO add-3 address is required (flash proper error message)
        # TODO add-4 city is required (flash proper error message)
        # TODO add-5 state is required (flash proper error message)
        # TODO add-6 country is required (flash proper error message)
        # TODO add-7 website is not required
        # flash error messages for required fields
        if name == "":
            flash("Enter company name", 'warning')
            return redirect(request.url)
        if address == "":
            flash("Enter Address", 'warning')
            return redirect(request.url)
        if city == "":
            flash("Enter city", 'warning')
            return redirect(request.url)
        if country == "":
            flash("Enter country", 'warning')
            return redirect("add")    
        if state == "":
            flash("Enter state", 'warning')
            return redirect(request.url)
        if website == '':
            website = 'N/A'
        has_error = False # use this to control whether or not an insert occurs
        

        if not has_error:
            try:
                

                ## Insert query to add a company
                result = DB.insertOne("""
                INSERT INTO IS601_MP3_Companies (name, address, city, country, state, zip, website)
                        VALUES (%(name)s, %(address)s, %(city)s, %(country)s, %(state)s, %(zip)s, %(website)s)
                        ON DUPLICATE KEY UPDATE address = %(address)s, city = %(city)s, country=%(country)s, state=%(state)s, zip=%(zip)s, website=%(website)s 
                """, {'name':name, 'address':address, 'city':city, 'country':country, 'state':state, 'zip':zip, 'website':website}) 
                # <-- TODO add-8 add query and add arguments
                if result.status:
                    flash("Added Company", "success")
            except Exception as e:
                # TODO add-9 make message user friendly
                

                ## flash message
                print(e)
                flash("Error adding the data, check again" + str(e), "danger")
        
    return render_template("add_company.html")

@company.route("/edit", methods=["GET", "POST"])
def edit():
    # TODO edit-1 request args id is required (flash proper error message)
    

    ## code to check for id, if no id flash a message
    id = request.args.get("id")
    if id is None:
        flash("ID is missing", "danger")
        return redirect("company.search")
    else: # TODO update this for TODO edit-1
        if request.method == "POST":
            # TODO edit-2 retrieve form data for name, address, city, state, country, zip, website
            

            ## retrieving the form data
            name = request.form.get('name')
            address = request.form.get('address')
            city = request.form.get('city')
            state = request.form.get('state')
            country = request.form.get('country')
            zipcode = request.form.get('zip')
            website = request.form.get('website')
            

            ## flash messages for required fields
            # TODO edit-3 name is required (flash proper error message)
            if name == '' or name == None:
                flash("Name is required", "danger")
                return redirect("add")
            # TODO edit-4 address is required (flash proper error message)
            if address == '' or address == None:
                flash("Address is required", "danger")
                return redirect("add")
            # TODO edit-5 city is required (flash proper error message)
            if city == '' or city == None:
                flash("City is required", "danger")
                return redirect("add")
            # TODO edit-6 state is required (flash proper error message)
            if state == '' or state == None:
                flash("State is required", "danger")
                return redirect("edit")
            # TODO edit-7 country is required (flash proper error message)
            if country == '' or country == None:
                flash("Country is required", "danger")
                return redirect("edit")
            # TODO edit-8 website is not required
            if website == '' or website == None:
                website = 'N/A'
            # 
            # note: call zip variable zipcode as zip is a built in function it could lead to issues
            data = [name, address, city, state, country, zipcode, website]
            data.append(id)
            try:
                # TODO edit-9 fill in proper update query
                

                ## Update query to record the edited data
                result = DB.update("""
                UPDATE IS601_MP3_Companies SET name = %s, address = %s, city = %s, state = %s, country = %s, zip = %s, website = %s
                WHERE id = %s
                """, *data)
                if result.status:
                    flash("Updated record", "success")
            except Exception as e:
                # TODO edit-10 make this user-friendly
                flash(f"Exception occured: {str(e)}", "danger")
        try:
            # TODO edit-11 fetch the updated data
            

            ## selecting the edited data
            result = DB.selectOne("SELECT name, address, city, country, state, zip, website FROM IS601_MP3_Companies WHERE id = %s", id)
            if result.status:
                row = result.row
                
        except Exception as e:
            # TODO edit-12 make this user-friendly
            flash(f"Exception occured: {str(e)}", "danger")
    # TODO edit-13 pass the company data to the render template
    return render_template("edit_company.html", row=row, state = row['state'], country = row['country'])

@company.route("/delete", methods=["GET"])
def delete():
    

    ## code for deleting company
    id = request.args.get('id')
    args = {**request.args}
    # TODO delete-1 delete company by id (unallocate any employees)
    # TODO delete-2 redirect to company search
    # TODO delete-3 pass all argument except id to this route
    # TODO delete-4 ensure a flash message shows for successful delete
    if id:
        DB.update("""UPDATE IS601_MP3_Employees SET company_id = %s where company_id = %s""", None, id)

project-3/BusinessManagement/views/geography.py
import pycountry
import json
from flask import Blueprint, request

geo = Blueprint("geo", __name__, url_prefix='/geo')
# TODO DO NOT EDIT
# these are javascript endpoints used from country_state_selector.html
@geo.route("/countries")
def countries():
    # extract just the data we need for our <select> options
    countries = map(lambda c: {"code": c.alpha_2, "name": c.name},list(pycountry.countries))
    return json.dumps(list(countries))

@geo.route("/states")
def states():
    # extract just the data we need for our <select> options
    status = list(map(lambda s: {"name": s.name, "code": s.code.split("-")[1]}, 
        list(pycountry.subdivisions.get(country_code=request.args.get('country_code', 'US')))))
    return json.dumps(status)

project-3/BusinessManagement/views/index.py
from flask import Blueprint, render_template
home = Blueprint('home', __name__, url_prefix='/')

# TODO DO NOT EDIT
@home.route('/')
def index():
    return render_template("index.html")

project-3/BusinessManagement/templates/add_company.html
{% extends "layout.html" %}
{% block title %}Add Company{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Add Company</div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for
            name
            address
            city
            website
            #}
            <label class="form-label" for="name">Name</label>
            <input class="form-control" id="name" name="name" type="text"/>
            <label class="form-label" for="address">Address</label>
            <input class="form-control" id="address" name="address" type="text"/>
            <label class="form-label" for="city">City</label>
            <input class="form-control" id="city" name="city" type="text"/>
            <label class="form-label" for="zip">Zip</label>
            <input class="form-control" id="zip" name="zip" type="number"/>
            <label class="form-label" for="website">Website</label>
            <input class="form-control" id="website" name="website" type="text"/>
            {# use this for country/state selection #}
            {% include "country_state_selector.html" %}
            <input type="submit" class="btn btn-primary" value="Save Company" />
        </form>
    </div>
</div>
{% endblock %}

project-3/BusinessManagement/templates/add_employee.html
{% extends "layout.html" %}
{% block title %}Add Employee{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Add Employee</div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for
            first_name
            last_name
            email
            #}
            <label class="form-label" for="first_name">First Name</label>
            <input class="form-control" id="first_name" name="first_name" type="text"/>
            <label class="form-label" for="last_name">Last Name</label>
            <input class="form-control" id="last_name" name="last_name" type="text"/>
            <label class="form-label" for="email">Email</label>
            <input class="form-control" id="email" name="email" type="email"/>
            {# use the below for company selection #}
            <label class="form-label" for="company">Company</label>
            {% include "company_dropdown.html" %}
            <input type="submit" class="btn btn-primary" value="Save Employee" />
        </form>
    </div>
</div>
{% endblock %}

project-3/BusinessManagement/templates/company_dropdown.html
{% macro company_dropdown(val="") %}
{% set comps = get_companies() %}
{# TODO DO NOT EDIT #}
<select class="form-select mb-3" name="company" value="{{val or ''}}">
    <option value="">No Company</option>
    {% for c in comps %}
    {# example of using external data setting and casting #}
    <option {{'selected' if val|string==c['id']|string}} value="{{c['id']}}">{{c['name']}}</option>
    {% endfor %}
</select>
{% endmacro %}

project-3/BusinessManagement/templates/country_state_selector.html
{# TODO DO NOT EDIT #}
{% set c = request.args.get("country", request.form.get("country", country or '')) %}
{% set s = request.args.get("state", request.form.get("state", state or '')) %}
{% if layout and layout == 'horizontal' %}
{# version for filter forms #}
<div class="col-12">
    <label class="visually-hidden" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="col-12">
    <label class="visually-hidden" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% else %}
{# version for add/edit forms #}
<div class="form-group mb-3">
    <label class="form-label" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="form-group mb-3">
    <label class="form-label" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% endif %}
<script>
    //gets called on page load and when the country selection changes
    const fetchStates = (country) => {
        //use jinja to return a string in the html template
        //this string will be as if we did let state = "whatever"
        let state = "{{s}}";
        console.log("fetching", country);
        fetch(`{{url_for('geo.states')}}?country_code=${country}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='state']");

                //if we had options, "clear" it to be the default option
                //so appending works
                if (ele.children.length > 1) {
                    ele.innerHTML = `<option value="">Select State...</option>`;
                }
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args state
                ele.value = state;
            });
    }
    window.addEventListener("load", () => {
        //use jinja to return a string in the html template
        //this string will be as if we did let country = "whatever"
        let country = "{{c}}";
        //get the country list from the endpoint
        fetch(`{{url_for('geo.countries')}}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='country']");
                ele.value = "";//clear the value so "onchange" works
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args country
                ele.value = country;
            })
            .finally(() => {
                //get the state list from the endpoint
                fetchStates(country);
            });
    });
</script>

project-3/BusinessManagement/templates/edit_company.html
{% extends "layout.html" %}
{% block title %}Edit Company{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Edit Company</div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for
            name
            address
            city
            website
            and prefill the fields with loaded company data
            #}
            <div class="form-group mb-3">
                <label class="form-label" for="name">Name</label>
                <input class="form-control" id="name" name="name" readonly value="{{row.name}}" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="address">Address</label>
                <input class="form-control" id="address" name="address" value="{{row.address}}" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="city">City</label>
                <input class="form-control" id="city" name="city" value="{{row.city}}" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="zip">Zip</label>
                <input class="form-control" id="zip" name="zip" value="{{row.zip}}" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="website">Website</label>
                <input class="form-control" id="website" name="website" value="{{row.website}}" />
            </div>
            {# use this for country/state selection #}
            {% include "country_state_selector.html" %}
            <input type="submit" class="btn btn-primary" value="Save Company" />
        </form>
    </div>
</div>
{% endblock %}

project-3/BusinessManagement/templates/index.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center text-warning">Ducks In a Row</div>
    <div class="w-50 mx-auto bg-light text-center caption border">At Ducks In A Row, we help
        organize your
        companies and
        employees all in one simple dashboard.</div>
        <div class="lead text-center">Brought to you by Anu (ac298) from section IS601-006
        {# TODO replace my name with your first name #}
        {# TODO replace my ucid with your ucid #}
        {# TODO replace both with your section (i.e., 005, 007, etc) #}
    </div>
</div>
{% endblock %}

project-3/BusinessManagement/templates/list_companies.html
{% extends "layout.html" %}
{% block title %}Company Directory{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center">Company Directory</div>
    {# TODO
    build a horizontal filter/sort form with
    name (company name)
    country/state (provided)
    sort/order (using allowed_columns and provided partial template)
    limit
    ensure all fields prefill with request arg data if provided
    #}
    <form class="row row-cols-lg-auto g-3 align-items-center" method="GET">
        <div class="col-12">
            <input type="text" name="name" class="form-control" id="name" placeholder="Name"
                value="{{request.args.get('name') or ''}}">
        </div>
        {% with layout = "horizontal" %}
        {% include "country_state_selector.html" %}
        {% endwith %}
        {% with cols = allowed_columns %}
        {% include "sort_filter.html" %}
        <div class="col-12">
            <input class="form-control" type="number" name="limit"  id="limit" placeholder="Limit" min="1" max="100"
                value="{{request.args.get('limit') or '10'}}">
        </div>
        {% endwith %}
        
        <div class="col-12">
            <input type="submit" class="btn btn-primary" value="Filter" />
        </div>
        <div class="col-12">
            <a href="?" class="btn btn-secondary">Reset</a>
        </div>
    </form>
    <div class="table-responsive">
    <table class="table">
        {% if rows and rows|length > 0 %}
        <thead>
            <tr class="text-capitalize">
                {# generate th tags for each column to display #}
                {# IMPORTANT use table column names as the headings, replace _ with space #}
                {% for r in rows[0] %}
                <th>{{r | replace("_", " ")}}</th>
                {% endfor %}
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {# generate tr with td tags for each piece of data #}
            {# if the td is for website, display it as a link where the text is "website" and the url is the
            website url #}
            {# in the last column add the following
            a view button that passes the company id to employee search (this will be a company employee
            directory) also pass company_name as an argument
            an edit button that passes the company id to company edit
            a delete button that passes the company id and the request args to the company delete route
            #}
            {% for r in rows %}
            <tr>
                {% for col,v in r.items() %}
                    {% if col == 'website' and value != 'N/A' %}
                        <td class="text-center"><a href="{{v}}" class="link-primary" target="_blank">Website</a></td>
                    {% else %}
                        <td>{{v}}</td>
                    {% endif %}
                {% endfor %}
                <td><a href="{{url_for('employee.search', company=r.get('id'), company_name=r.get('name'))}}">View</a>
                    <a href="{{url_for('company.edit', id=r.get('id'))}}">Edit</a>
                    {# **request.args spreads the key value pairs to be part of the url#}
                    {# the idea is to pass it to the next route #}
                    <a href="{{url_for('company.delete', id=r.get('id'), **request.args)}}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        {% else %}
        <tbody>
            <tr>
                <td colspan="100%">No results to show</td>
            </tr>
        </tbody>
        {% endif %}
    </table>
    </div>
</div>
{% endblock %}

project-3/BusinessManagement/templates/nav.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        {# TODO replace my ucid mt85 with your ucid in the below a tag #}
        <a class="navbar-brand" href="{{url_for('home.index')}}">DIAR-ac298</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {# TODO fill in the relevant hrefs using url_for() #}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- company dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Company
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('company.search')}}">Search</a></li>
                        <li><a class="dropdown-item" href="{{url_for('company.add')}}">Add</a></li>

                    </ul>
                </li>
                <!-- employee dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Employee
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('employee.search')}}">Search</a></li>
                        <li><a class="dropdown-item" href="{{url_for('employee.add')}}">Add</a></li>
                    </ul>
                </li>
                <!-- admin dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Admin
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('admin.importCSV')}}">Import</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>